name: clean_architecture
description: "Clean Architecture Posts app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  #Packages
  # Bloc state management
  flutter_bloc: ^8.1.6
  # Remote API
  internet_connection_checker: ^1.0.0+1
  http: ^1.2.1
  # Functional programming in Dart
  dartz: ^0.10.1
  # Value equality
  equatable: ^2.0.5
  # Service Locator (DE)
  get_it: ^7.7.0
  # Local cache
  shared_preferences: ^2.2.3
  # Connectivity
  connectivity_plus: ^6.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
